### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by MrYANG23** [KevinMIN95/StyleSpeech#7]
https://github.com/KevinMIN95/StyleSpeech/blob/ddff11e680e7c1491df7733fa498aa07b0be1c5f/preprocessors/libritts.py#L130
the remove_outlier here return none 
![image](https://user-images.githubusercontent.com/38352877/138016839-db61b3d5-dcd6-4e15-95c7-03e2d77ae0a4.png)
and  in line 51,52:
            list indices must be integers or slices, not list

**Comment by guoaoo** [comment]
x = np.array(x)

***

return x.to_list()

**Comment by hcy71o** [comment]
Revise the code as below
in preprocessors/libritts.py
BEFORE 
if len([f for f in f0 if f != 0]) ==0 or len([e for e in energy if e != 0]):
AFTER
if len([f for f in f0 if f != 0]) ==0 or len([e for e in energy if e != 0])==0:

**Comment by fish0131** [comment]
When I ran the preprocess.py, I would get this error: IndexError: cannot do a non-empty take from an empty axes.

Traceback (most recent call last):
  File "preprocess.py", line 54, in <module>
    main(preprocessor, args.data_path, args.output_path)
  File "preprocess.py", line 39, in main
    datas = preprocessor.build_from_path(data_dir, out_dir)
  File "/media/fish-bsp/fish_4TB/Audio/StyleSpeech-main/preprocessors/libritts.py", line 132, in build_from_path
    f0 = remove_outlier(f0)

How can I revise the code to let it run successfully? Thanks.
